const MILLSECONDS_PER_MINUTE = 60 * 1000
export const ACCESS_TOKEN_EXPIRE_TIME = 60 * MILLSECONDS_PER_MINUTE

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL

export const PAGINATION_LIMIT_DEFAULT = 10
